### ISSUE TITLE
error for different video

### ISSUE THREAD

**Issue by yashika000** [Kilichbek/Lane-Detection#1]
If I am running this code for different video and try to run then it is giving following error:
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.9) /home/opencv/modules/core/src/matrix.cpp:466: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'

**Comment by Kilichbek** [comment]
Hi, @yashika000. It is related to sliding windows' size. I assume the windows are getting outside a video frame. You need to manually adjust the size of sliding windows for your video.

**Comment by yashika000** [comment]
Hi @Kilichbek ,I have done changes in utils.h file where height and width is manually given but still the same error is coming..

**Comment by Kilichbek** [comment]
@yashika000, please also check whether the windows are getting outside the frame regions!

**Comment by yashika000** [comment]
Worked after resizing the windows!
